version: '3.8'

services:
  # PostgreSQL Database
  # Shared by Synapse and MAS
  postgres:
    image: postgres:16-alpine
    container_name: matrix-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: synapse
      POSTGRES_USER: synapse
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=C"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    networks:
      - matrix
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U synapse"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Synapse - Matrix Homeserver
  synapse:
    image: matrixdotorg/synapse:latest
    container_name: matrix-synapse
    restart: unless-stopped
    ports:
      - "8008:8008"  # Client API (expose to reverse proxy)
      - "8448:8448"  # Federation API (expose if federating)
    volumes:
      - ./synapse/data:/data
      - ./synapse/config/homeserver.yaml:/data/homeserver.yaml:ro
    environment:
      - SYNAPSE_CONFIG_PATH=/data/homeserver.yaml
    networks:
      - matrix
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8008/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Matrix Authentication Service (MAS)
  # Handles OIDC authentication for Synapse
  mas:
    image: ghcr.io/element-hq/matrix-authentication-service:0.13.3
    container_name: matrix-mas
    restart: unless-stopped
    ports:
      - "8080:8080"  # MAS API (expose to reverse proxy)
    volumes:
      - ./mas/config/config.yaml:/config.yaml:ro
      - ./mas/data:/data
    command: ["server", "-c", "/config.yaml"]
    networks:
      - matrix
    depends_on:
      postgres:
        condition: service_healthy
      synapse:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Element Web - Matrix Web Client
  element:
    image: vectorim/element-web:latest
    container_name: matrix-element
    restart: unless-stopped
    ports:
      - "8082:80"  # Web interface (expose to reverse proxy)
    volumes:
      - ./element/config/config.json:/app/config.json:ro
    networks:
      - matrix

  # Element Admin - Admin Interface
  element-admin:
    image: awesometechnologies/synapse-admin:latest
    container_name: matrix-element-admin
    restart: unless-stopped
    ports:
      - "8081:80"  # Admin interface (consider restricting access)
    networks:
      - matrix

networks:
  matrix:
    driver: bridge

# Notes:
# 1. Ensure .env file is created from .env.template with all secrets
# 2. Configure homeserver.yaml, mas config.yaml, and element config.json
# 3. Set up reverse proxy (Caddy) to handle SSL/TLS termination
# 4. Consider using Docker secrets for production deployments
# 5. Adjust port mappings if running multiple services on same host
